version: "3.9"

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"

  front:
    build:  ./front
    container_name: react-frontend
    ports:
      - "3000:3000"
    environment:
     - VITE_BACKEND_URL=http://backend:8000
    depends_on:
     - backend